 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace C2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID SettingOK = (Nettention.Proud.RmiID)5000+1;
			public const Nettention.Proud.RmiID CardInfo = (Nettention.Proud.RmiID)5000+2;
			public const Nettention.Proud.RmiID ClearInfo = (Nettention.Proud.RmiID)5000+3;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			SettingOK,
			CardInfo,
			ClearInfo,
		};
	}
}

				 
