




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
using System.Net;
using GameItem;

namespace C2C
{
	internal class Stub:Nettention.Proud.RmiStub
	{
public AfterRmiInvocationDelegate AfterRmiInvocation = delegate(Nettention.Proud.AfterRmiSummary summary) {};
public BeforeRmiInvocationDelegate BeforeRmiInvocation = delegate(Nettention.Proud.BeforeRmiSummary summary) {};

		public delegate bool SettingOKDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext);  
		public SettingOKDelegate SettingOK = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext)
		{ 
			return false;
		};
		public delegate bool CardInfoDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, CardInfo_send info);  
		public CardInfoDelegate CardInfo = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, CardInfo_send info)
		{ 
			return false;
		};
		public delegate bool ClearInfoDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext);  
		public ClearInfoDelegate ClearInfo = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext)
		{ 
			return false;
		};
		public delegate bool InitDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int hostNum);  
		public InitDelegate Init = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int hostNum)
		{ 
			return false;
		};
		public delegate bool HandCardCountDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int num);  
		public HandCardCountDelegate HandCardCount = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int num)
		{ 
			return false;
		};
		public delegate bool ReturnInfoDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int fieldNum);  
		public ReturnInfoDelegate ReturnInfo = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int fieldNum)
		{ 
			return false;
		};
		public delegate bool SummonInfoDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, CardInfo_send info);  
		public SummonInfoDelegate SummonInfo = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, CardInfo_send info)
		{ 
			return false;
		};
		public delegate bool RandomInfoDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, bool ran1, bool ran2, bool ran3, bool ran4, bool ran5);  
		public RandomInfoDelegate RandomInfo = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, bool ran1, bool ran2, bool ran3, bool ran4, bool ran5)
		{ 
			return false;
		};
		public delegate bool InitInfoDelegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int cardNum);  
		public InitInfoDelegate InitInfo = delegate(Nettention.Proud.HostID remote,Nettention.Proud.RmiContext rmiContext, int cardNum)
		{ 
			return false;
		};
	public override bool ProcessReceivedMessage(Nettention.Proud.ReceivedMessage pa, Object hostTag) 
	{
		Nettention.Proud.HostID remote=pa.RemoteHostID;
		if(remote==Nettention.Proud.HostID.HostID_None)
		{
			ShowUnknownHostIDWarning(remote);
		}

		Nettention.Proud.Message __msg=pa.ReadOnlyMessage;
		int orgReadOffset = __msg.ReadOffset;
        Nettention.Proud.RmiID __rmiID = Nettention.Proud.RmiID.RmiID_None;
        if (!__msg.Read( out __rmiID))
            goto __fail;
					
		switch(__rmiID)
		{
case Common.SettingOK:
	{
		Nettention.Proud.RmiContext ctx=new Nettention.Proud.RmiContext();
		ctx.sentFrom=pa.RemoteHostID;
		ctx.relayed=pa.IsRelayed;
		ctx.hostTag=hostTag;
		ctx.encryptMode = pa.EncryptMode;
		ctx.compressMode = pa.CompressMode;
			
		core.PostCheckReadMessage(__msg, RmiName_SettingOK);
		if(enableNotifyCallFromStub==true)
		{
			string parameterString="";
						NotifyCallFromStub(Common.SettingOK, RmiName_SettingOK,parameterString);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
			summary.rmiID = Common.SettingOK;
			summary.rmiName = RmiName_SettingOK;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			BeforeRmiInvocation(summary);
		}
			
		long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();
			
		// Call this method.
		bool __ret=SettingOK (remote,ctx  );
			
		if(__ret==false)
		{
			// Error: RMI function that a user did not create has been called. 
			core.ShowNotImplementedRmiWarning(RmiName_SettingOK);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
			summary.rmiID = Common.SettingOK;
			summary.rmiName = RmiName_SettingOK;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
			AfterRmiInvocation(summary);
		}
	}
	break;
case Common.CardInfo:
	{
		Nettention.Proud.RmiContext ctx=new Nettention.Proud.RmiContext();
		ctx.sentFrom=pa.RemoteHostID;
		ctx.relayed=pa.IsRelayed;
		ctx.hostTag=hostTag;
		ctx.encryptMode = pa.EncryptMode;
		ctx.compressMode = pa.CompressMode;
			
		CardInfo_send info; CardClient.Marshaler.Read(__msg,out info);	
core.PostCheckReadMessage(__msg, RmiName_CardInfo);
		if(enableNotifyCallFromStub==true)
		{
			string parameterString="";
			parameterString+=info.ToString()+",";
			NotifyCallFromStub(Common.CardInfo, RmiName_CardInfo,parameterString);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
			summary.rmiID = Common.CardInfo;
			summary.rmiName = RmiName_CardInfo;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			BeforeRmiInvocation(summary);
		}
			
		long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();
			
		// Call this method.
		bool __ret=CardInfo (remote,ctx , info );
			
		if(__ret==false)
		{
			// Error: RMI function that a user did not create has been called. 
			core.ShowNotImplementedRmiWarning(RmiName_CardInfo);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
			summary.rmiID = Common.CardInfo;
			summary.rmiName = RmiName_CardInfo;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
			AfterRmiInvocation(summary);
		}
	}
	break;
case Common.ClearInfo:
	{
		Nettention.Proud.RmiContext ctx=new Nettention.Proud.RmiContext();
		ctx.sentFrom=pa.RemoteHostID;
		ctx.relayed=pa.IsRelayed;
		ctx.hostTag=hostTag;
		ctx.encryptMode = pa.EncryptMode;
		ctx.compressMode = pa.CompressMode;
			
		core.PostCheckReadMessage(__msg, RmiName_ClearInfo);
		if(enableNotifyCallFromStub==true)
		{
			string parameterString="";
						NotifyCallFromStub(Common.ClearInfo, RmiName_ClearInfo,parameterString);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
			summary.rmiID = Common.ClearInfo;
			summary.rmiName = RmiName_ClearInfo;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			BeforeRmiInvocation(summary);
		}
			
		long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();
			
		// Call this method.
		bool __ret=ClearInfo (remote,ctx  );
			
		if(__ret==false)
		{
			// Error: RMI function that a user did not create has been called. 
			core.ShowNotImplementedRmiWarning(RmiName_ClearInfo);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
			summary.rmiID = Common.ClearInfo;
			summary.rmiName = RmiName_ClearInfo;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
			AfterRmiInvocation(summary);
		}
	}
	break;
case Common.Init:
	{
		Nettention.Proud.RmiContext ctx=new Nettention.Proud.RmiContext();
		ctx.sentFrom=pa.RemoteHostID;
		ctx.relayed=pa.IsRelayed;
		ctx.hostTag=hostTag;
		ctx.encryptMode = pa.EncryptMode;
		ctx.compressMode = pa.CompressMode;
			
		int hostNum; CardClient.Marshaler.Read(__msg,out hostNum);	
core.PostCheckReadMessage(__msg, RmiName_Init);
		if(enableNotifyCallFromStub==true)
		{
			string parameterString="";
			parameterString+=hostNum.ToString()+",";
			NotifyCallFromStub(Common.Init, RmiName_Init,parameterString);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
			summary.rmiID = Common.Init;
			summary.rmiName = RmiName_Init;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			BeforeRmiInvocation(summary);
		}
			
		long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();
			
		// Call this method.
		bool __ret=Init (remote,ctx , hostNum );
			
		if(__ret==false)
		{
			// Error: RMI function that a user did not create has been called. 
			core.ShowNotImplementedRmiWarning(RmiName_Init);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
			summary.rmiID = Common.Init;
			summary.rmiName = RmiName_Init;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
			AfterRmiInvocation(summary);
		}
	}
	break;
case Common.HandCardCount:
	{
		Nettention.Proud.RmiContext ctx=new Nettention.Proud.RmiContext();
		ctx.sentFrom=pa.RemoteHostID;
		ctx.relayed=pa.IsRelayed;
		ctx.hostTag=hostTag;
		ctx.encryptMode = pa.EncryptMode;
		ctx.compressMode = pa.CompressMode;
			
		int num; CardClient.Marshaler.Read(__msg,out num);	
core.PostCheckReadMessage(__msg, RmiName_HandCardCount);
		if(enableNotifyCallFromStub==true)
		{
			string parameterString="";
			parameterString+=num.ToString()+",";
			NotifyCallFromStub(Common.HandCardCount, RmiName_HandCardCount,parameterString);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
			summary.rmiID = Common.HandCardCount;
			summary.rmiName = RmiName_HandCardCount;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			BeforeRmiInvocation(summary);
		}
			
		long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();
			
		// Call this method.
		bool __ret=HandCardCount (remote,ctx , num );
			
		if(__ret==false)
		{
			// Error: RMI function that a user did not create has been called. 
			core.ShowNotImplementedRmiWarning(RmiName_HandCardCount);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
			summary.rmiID = Common.HandCardCount;
			summary.rmiName = RmiName_HandCardCount;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
			AfterRmiInvocation(summary);
		}
	}
	break;
case Common.ReturnInfo:
	{
		Nettention.Proud.RmiContext ctx=new Nettention.Proud.RmiContext();
		ctx.sentFrom=pa.RemoteHostID;
		ctx.relayed=pa.IsRelayed;
		ctx.hostTag=hostTag;
		ctx.encryptMode = pa.EncryptMode;
		ctx.compressMode = pa.CompressMode;
			
		int fieldNum; CardClient.Marshaler.Read(__msg,out fieldNum);	
core.PostCheckReadMessage(__msg, RmiName_ReturnInfo);
		if(enableNotifyCallFromStub==true)
		{
			string parameterString="";
			parameterString+=fieldNum.ToString()+",";
			NotifyCallFromStub(Common.ReturnInfo, RmiName_ReturnInfo,parameterString);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
			summary.rmiID = Common.ReturnInfo;
			summary.rmiName = RmiName_ReturnInfo;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			BeforeRmiInvocation(summary);
		}
			
		long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();
			
		// Call this method.
		bool __ret=ReturnInfo (remote,ctx , fieldNum );
			
		if(__ret==false)
		{
			// Error: RMI function that a user did not create has been called. 
			core.ShowNotImplementedRmiWarning(RmiName_ReturnInfo);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
			summary.rmiID = Common.ReturnInfo;
			summary.rmiName = RmiName_ReturnInfo;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
			AfterRmiInvocation(summary);
		}
	}
	break;
case Common.SummonInfo:
	{
		Nettention.Proud.RmiContext ctx=new Nettention.Proud.RmiContext();
		ctx.sentFrom=pa.RemoteHostID;
		ctx.relayed=pa.IsRelayed;
		ctx.hostTag=hostTag;
		ctx.encryptMode = pa.EncryptMode;
		ctx.compressMode = pa.CompressMode;
			
		CardInfo_send info; CardClient.Marshaler.Read(__msg,out info);	
core.PostCheckReadMessage(__msg, RmiName_SummonInfo);
		if(enableNotifyCallFromStub==true)
		{
			string parameterString="";
			parameterString+=info.ToString()+",";
			NotifyCallFromStub(Common.SummonInfo, RmiName_SummonInfo,parameterString);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
			summary.rmiID = Common.SummonInfo;
			summary.rmiName = RmiName_SummonInfo;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			BeforeRmiInvocation(summary);
		}
			
		long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();
			
		// Call this method.
		bool __ret=SummonInfo (remote,ctx , info );
			
		if(__ret==false)
		{
			// Error: RMI function that a user did not create has been called. 
			core.ShowNotImplementedRmiWarning(RmiName_SummonInfo);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
			summary.rmiID = Common.SummonInfo;
			summary.rmiName = RmiName_SummonInfo;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
			AfterRmiInvocation(summary);
		}
	}
	break;
case Common.RandomInfo:
	{
		Nettention.Proud.RmiContext ctx=new Nettention.Proud.RmiContext();
		ctx.sentFrom=pa.RemoteHostID;
		ctx.relayed=pa.IsRelayed;
		ctx.hostTag=hostTag;
		ctx.encryptMode = pa.EncryptMode;
		ctx.compressMode = pa.CompressMode;
			
		bool ran1; CardClient.Marshaler.Read(__msg,out ran1);	
bool ran2; CardClient.Marshaler.Read(__msg,out ran2);	
bool ran3; CardClient.Marshaler.Read(__msg,out ran3);	
bool ran4; CardClient.Marshaler.Read(__msg,out ran4);	
bool ran5; CardClient.Marshaler.Read(__msg,out ran5);	
core.PostCheckReadMessage(__msg, RmiName_RandomInfo);
		if(enableNotifyCallFromStub==true)
		{
			string parameterString="";
			parameterString+=ran1.ToString()+",";
parameterString+=ran2.ToString()+",";
parameterString+=ran3.ToString()+",";
parameterString+=ran4.ToString()+",";
parameterString+=ran5.ToString()+",";
			NotifyCallFromStub(Common.RandomInfo, RmiName_RandomInfo,parameterString);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
			summary.rmiID = Common.RandomInfo;
			summary.rmiName = RmiName_RandomInfo;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			BeforeRmiInvocation(summary);
		}
			
		long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();
			
		// Call this method.
		bool __ret=RandomInfo (remote,ctx , ran1, ran2, ran3, ran4, ran5 );
			
		if(__ret==false)
		{
			// Error: RMI function that a user did not create has been called. 
			core.ShowNotImplementedRmiWarning(RmiName_RandomInfo);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
			summary.rmiID = Common.RandomInfo;
			summary.rmiName = RmiName_RandomInfo;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
			AfterRmiInvocation(summary);
		}
	}
	break;
case Common.InitInfo:
	{
		Nettention.Proud.RmiContext ctx=new Nettention.Proud.RmiContext();
		ctx.sentFrom=pa.RemoteHostID;
		ctx.relayed=pa.IsRelayed;
		ctx.hostTag=hostTag;
		ctx.encryptMode = pa.EncryptMode;
		ctx.compressMode = pa.CompressMode;
			
		int cardNum; CardClient.Marshaler.Read(__msg,out cardNum);	
core.PostCheckReadMessage(__msg, RmiName_InitInfo);
		if(enableNotifyCallFromStub==true)
		{
			string parameterString="";
			parameterString+=cardNum.ToString()+",";
			NotifyCallFromStub(Common.InitInfo, RmiName_InitInfo,parameterString);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.BeforeRmiSummary summary = new Nettention.Proud.BeforeRmiSummary();
			summary.rmiID = Common.InitInfo;
			summary.rmiName = RmiName_InitInfo;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			BeforeRmiInvocation(summary);
		}
			
		long t0 = Nettention.Proud.PreciseCurrentTime.GetTimeMs();
			
		// Call this method.
		bool __ret=InitInfo (remote,ctx , cardNum );
			
		if(__ret==false)
		{
			// Error: RMI function that a user did not create has been called. 
			core.ShowNotImplementedRmiWarning(RmiName_InitInfo);
		}
			
		if(enableStubProfiling)
		{
			Nettention.Proud.AfterRmiSummary summary = new Nettention.Proud.AfterRmiSummary();
			summary.rmiID = Common.InitInfo;
			summary.rmiName = RmiName_InitInfo;
			summary.hostID = remote;
			summary.hostTag = hostTag;
			summary.elapsedTime = Nettention.Proud.PreciseCurrentTime.GetTimeMs()-t0;
			AfterRmiInvocation(summary);
		}
	}
	break;
		default:
			 goto __fail;
		}
		return true;
__fail:
	  {
			__msg.ReadOffset = orgReadOffset;
			return false;
	  }
	}
// RMI name declaration.
// It is the unique pointer that indicates RMI name such as RMI profiler.
const string RmiName_SettingOK="SettingOK";
const string RmiName_CardInfo="CardInfo";
const string RmiName_ClearInfo="ClearInfo";
const string RmiName_Init="Init";
const string RmiName_HandCardCount="HandCardCount";
const string RmiName_ReturnInfo="ReturnInfo";
const string RmiName_SummonInfo="SummonInfo";
const string RmiName_RandomInfo="RandomInfo";
const string RmiName_InitInfo="InitInfo";
       
const string RmiName_First = RmiName_SettingOK;
		public override Nettention.Proud.RmiID[] GetRmiIDList { get{return Common.RmiIDList;} }
		
	}
}

